### ISSUE TITLE
regex on mip-workspaces

### ISSUE THREAD

**Issue by avelino** [gaudecker/mip-mode#4]
example: `~/src/*/*`

On golang used this path by sample: **~/src/github.com/avelino/slugify**

**Comment by gaudecker** [comment]
If I understand correctly, you want to insert directories into `mip-workspaces` that match some regex?

If so, you could write a function to list directories (using `directory-files` for example, just remember to filter out any files, `.` and `..`) and then filter out directories that don't match your regex.

Then you just add the results of your function to `mip-workspaces`.

**Comment by avelino** [comment]
Thanks :D
